### PR TITLE
created a homepage and rendered a list of movies

### PR DESCRIPTION
**Pull request by Developer-Kingz**
created a homepage and rendered a list of movies and also buttons for comment and reservations popup

### CODE REVIEW

**Comment by geekelo** [comment]
Hi @Developer-Kingz  , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] Kindly note that there are linter errors on your last commit.

I suggest that you fix the current linter errors to ensure that the dev branch is completely free of linter errors 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by geekelo** [comment]
@Eccb7 I was hoping that the linters are first fixed so we don't have to start fixing the linter errors individually after pulling

**Comment by Eccb7** [comment]
I talked to Kingsley and he said we can work on the linters after finishing
since he was still working on the like icon

**Comment by geekelo** [comment]
@Eccb7 Alright. Thanks for the update. Could you please review my pull request so I can work on the API? https://github.com/geekelo/kingflix/pull/25

Thanks in Advance

**Pull request merged**
